import { useEffect, useMemo, useState } from "react";
import { toUserFacingErrorMessage } from "../../lib/userFacingError";
import { catalogApi, uploadManagedImage } from "../../services/admin/catalogApi";
import { operationsApi } from "../../services/admin/operationsApi";
import type { MediaPurpose, MediaStorageState } from "../../types/adminCatalog";
import { AdminListPage, exportCsv } from "./AdminListPage";
import { ManagedMediaControl, type ManagedMediaItem } from "./ManagedMediaControl";

type Kind = "returns" | "reviews" | "support";
type Props = { token: string; storage: MediaStorageState; mode?: "list" | "create" | "edit"; recordId?: string | null; onNavigate: (path: string, replace?: boolean) => void };
const safeError = (error: unknown) => toUserFacingErrorMessage(error, "The request could not be completed.");
const configs = {
  returns: { title: "Returns", description: "Inspect requests, evidence, restocking, and refund progress.", purpose: "return_evidence" as MediaPurpose, mediaLabel: "Return evidence" },
  reviews: { title: "Reviews", description: "Moderate ratings, customer feedback, reports, and product media.", purpose: "review_image" as MediaPurpose, mediaLabel: "Review image" },
  support: { title: "Support", description: "Manage customer conversations, order-linked issues, and attachments.", purpose: "support_attachment" as MediaPurpose, mediaLabel: "Support attachment" },
};

function mediaItems(record: Record<string, unknown> | null, purpose: MediaPurpose, label: string): ManagedMediaItem[] {
  const attached = Array.isArray(record?.media) ? record.media as Array<Record<string, unknown>> : [];
  return [...attached.map((item) => ({ id: String(item.upload_uuid ?? item.uuid ?? item.id), purpose, label, url: typeof item.url === "string" ? item.url : null })), { id: "new", purpose, label: `Add ${label.toLowerCase()}`, url: null }];
}

function OperationalPanel({ kind, token, storage, mode = "list", recordId, onNavigate }: Props & { kind: Kind }) {
  const config = configs[kind];
  const [rows, setRows] = useState<Array<Record<string, unknown>>>([]); const [record, setRecord] = useState<Record<string, unknown> | null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1); const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set()); const [message, setMessage] = useState(`Loading ${kind}...`); const [progress, setProgress] = useState<number | null>(null); const [mediaError, setMediaError] = useState("");
  const load = async () => { try { const result = kind === "returns" ? await operationsApi.returns(token) : kind === "reviews" ? await operationsApi.reviews(token) : await operationsApi.support(token); setRows(result.data); setMessage(result.data.length ? "" : `No ${kind} found.`); } catch (error) { setMessage(safeError(error)); } };
  const loadRecord = async (uuid: string) => { try { if (kind === "returns") setRecord((await operationsApi.returnRequest(token, uuid)).return); else if (kind === "reviews") setRecord((await operationsApi.review(token, uuid)).review); else setRecord((await operationsApi.supportTicket(token, uuid)).ticket); setMessage(""); } catch (error) { setMessage(safeError(error)); } };
  useEffect(() => { void load(); }, [token, kind]);
  useEffect(() => { if (mode === "edit" && recordId) void loadRecord(recordId); }, [mode, recordId, token, kind]);
  const filtered = useMemo(() => rows.filter((row) => (!status || String(row.status) === status) && JSON.stringify(row).toLowerCase().includes(search.toLowerCase())).sort((left, right) => { const a = String(left.created_at ?? left.updated_at ?? ""); const b = String(right.created_at ?? right.updated_at ?? ""); return sort === "oldest" ? a.localeCompare(b) : b.localeCompare(a); }), [rows, search, status, sort]);
  const pageSize = 20; const pageItems = filtered.slice((page - 1) * pageSize, page * pageSize); const allSelected = pageItems.length > 0 && pageItems.every((row) => selectedIds.has(String(row.uuid)));
  const identifier = (row: Record<string, unknown>) => String(row.return_number ?? row.ticket_number ?? row.title ?? row.uuid);
  const secondary = (row: Record<string, unknown>) => kind === "returns" ? `Order ${String((row.order as Record<string, unknown> | undefined)?.order_number ?? "—")}` : kind === "reviews" ? `${Number(row.rating ?? 0)} stars · ${String((row.user as Record<string, unknown> | undefined)?.email ?? "Customer")}` : String(row.subject ?? "Customer support ticket");
  async function apply(uuid: string, action: string) { try { if (kind === "returns") await operationsApi.returnAction(token, uuid, { action, ...(action === "refund" ? { amount_minor: Number(window.prompt("Manual refund minor units") ?? 0) } : {}) }); else if (kind === "reviews") await operationsApi.reviewAction(token, uuid, { action }); else if (action === "close") await operationsApi.closeSupport(token, uuid); await load(); if (mode === "edit") await loadRecord(uuid); setMessage("Record updated."); } catch (error) { setMessage(safeError(error)); } }
  async function bulk(action: string) { const targets = rows.filter((row) => selectedIds.has(String(row.uuid))); if (!targets.length || !window.confirm(`${action[0].toUpperCase() + action.slice(1)} ${targets.length} selected records?`)) return; for (const row of targets) await apply(String(row.uuid), action); setSelectedIds(new Set()); }
  async function upload(file: File) { if (!recordId) return; setProgress(0); setMediaError(""); try { await uploadManagedImage({ token, purpose: config.purpose, targetUuid: recordId, file, onProgress: setProgress }); await loadRecord(recordId); } catch (error) { setMediaError(safeError(error)); } finally { setProgress(null); } }
  async function removeMedia(item: ManagedMediaItem) { if (item.id === "new" || !recordId) return; try { await catalogApi.deleteManagedUpload(token, item.id); await loadRecord(recordId); } catch (error) { setMediaError(safeError(error)); } }
  const bulkPrimary = kind === "returns" ? "approve" : kind === "reviews" ? "approve" : "close"; const bulkArchive = kind === "returns" ? "close" : kind === "reviews" ? "hide" : "close";
  if (mode === "list") return <AdminListPage bulkActions={[{ label: `Bulk ${bulkPrimary}`, onClick: () => void bulk(bulkPrimary) }, { label: "Bulk archive", onClick: () => void bulk(bulkArchive) }, { label: "Bulk delete", tone: "danger", onClick: () => void bulk(bulkArchive) }]} count={filtered.length} description={config.description} filters={<select className="min-h-11 rounded-xl border border-neutral-200 px-4 text-sm font-bold" onChange={(event) => { setStatus(event.target.value); setPage(1); }} value={status}><option value="">All statuses</option>{Array.from(new Set(rows.map((row) => String(row.status)))).map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select>} onExport={() => exportCsv(`${kind}.csv`, filtered.map((row) => ({ record: identifier(row), status: row.status, details: secondary(row), created: row.created_at ?? row.updated_at })))} onPage={setPage} onSearch={setSearch} onSort={setSort} page={page} pageSize={pageSize} search={search} selectedCount={selectedIds.size} sort={sort} sortOptions={[{ value: "newest", label: "Sort: Newest" }, { value: "oldest", label: "Sort: Oldest" }]} title={config.title} total={filtered.length}><table className="min-w-[850px] w-full text-left text-sm"><thead className="bg-neutral-50"><tr>{["", "Record", "Details", "Status", "Updated", ""].map((header, index) => <th className="px-4 py-4 text-xs font-black uppercase tracking-[0.14em] text-neutral-500" key={`${header}-${index}`}>{index === 0 ? <input aria-label="Select page" checked={allSelected} onChange={() => setSelectedIds((current) => { const next = new Set(current); pageItems.forEach((row) => allSelected ? next.delete(String(row.uuid)) : next.add(String(row.uuid))); return next; })} type="checkbox" /> : header}</th>)}</tr></thead><tbody>{pageItems.map((row) => <tr className="border-t border-neutral-100 hover:bg-orange-50/30" key={String(row.uuid)}><td className="px-4 py-4"><input aria-label={`Select ${identifier(row)}`} checked={selectedIds.has(String(row.uuid))} onChange={() => setSelectedIds((current) => { const next = new Set(current); const id = String(row.uuid); next.has(id) ? next.delete(id) : next.add(id); return next; })} type="checkbox" /></td><td className="px-4 py-4"><button className="font-black hover:text-citrus-600" onClick={() => onNavigate(`/admin/${kind}/${String(row.uuid)}/edit`)} type="button">{identifier(row)}</button></td><td className="max-w-md px-4 py-4 text-neutral-600">{secondary(row)}</td><td className="px-4 py-4 capitalize">{String(row.status).replaceAll("_", " ")}</td><td className="px-4 py-4">{row.updated_at || row.created_at ? new Date(String(row.updated_at ?? row.created_at)).toLocaleString() : "—"}</td><td className="px-4 py-4"><button className="font-black text-leaf-700" onClick={() => onNavigate(`/admin/${kind}/${String(row.uuid)}/edit`)} type="button">Edit</button></td></tr>)}</tbody></table></AdminListPage>;
  const actions = kind === "returns" ? ["approve", "received", "refund", "close"] : kind === "reviews" ? ["approve", "reject", "hide", "restore"] : ["close"];
  return <section className="grid gap-6 rounded-[28px] border border-neutral-200 bg-white p-5 shadow-soft sm:p-8"><button className="w-fit text-sm font-black text-leaf-700" onClick={() => onNavigate(`/admin/${kind}`)} type="button">← {config.title}</button>{message ? <p className="rounded-2xl bg-neutral-50 p-3 text-sm">{message}</p> : null}{record ? <><div className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-citrus-500">Edit {kind === "support" ? "support ticket" : kind.slice(0, -1)}</p><h2 className="mt-2 text-3xl font-black">{identifier(record)}</h2><p className="mt-2 max-w-3xl text-sm text-neutral-600">{secondary(record)}</p></div><div className="flex flex-wrap gap-2">{actions.map((action) => <button className="rounded-2xl border border-neutral-200 px-4 py-3 text-xs font-black capitalize" key={action} onClick={() => void apply(String(record.uuid), action)} type="button">{action}</button>)}</div></div><section className="rounded-2xl border border-neutral-200 p-5"><h3 className="text-lg font-black">Record details</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-neutral-700">{String(record.body ?? record.description ?? record.subject ?? "No additional details.")}</p></section><section className="rounded-2xl border border-neutral-200 p-5"><h3 className="text-lg font-black">Media</h3><ManagedMediaControl allowReplace={false} entityId={String(record.uuid)} entityType={kind === "support" ? "support-ticket" : kind.slice(0, -1)} error={mediaError} items={mediaItems(record, config.purpose, config.mediaLabel)} onRemove={(item) => void removeMedia(item)} onUpload={(_purpose, file) => void upload(file)} progress={progress} storage={storage} /></section>{kind === "support" ? <section className="rounded-2xl border border-neutral-200 p-5"><h3 className="text-lg font-black">Reply</h3><button className="mt-3 rounded-2xl bg-leaf-600 px-5 py-3 text-sm font-black text-white" onClick={() => { const body = window.prompt("Reply"); if (body) void operationsApi.supportMessage(token, String(record.uuid), { body, customer_visible: true }).then(() => loadRecord(String(record.uuid))).catch((error) => setMessage(safeError(error))); }} type="button">Send reply</button></section> : null}</> : null}</section>;
}

export const EnterpriseReturnsAdminPanel = (props: Props) => <OperationalPanel {...props} kind="returns" />;
export const EnterpriseReviewsAdminPanel = (props: Props) => <OperationalPanel {...props} kind="reviews" />;
export const EnterpriseSupportAdminPanel = (props: Props) => <OperationalPanel {...props} kind="support" />;
